# Práctica 2: Ejercicios propuestos
# Inteligencia Artificial
# Grado en Ingeniería Informática - Ingeniería del Software
# Universidad de Sevilla

Los ejercicios que se plantean a continuación tienen como objetivo el practicar con la biblioteca [Keras](https://keras.io/2.15/api/) de Python.

In [1]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

### Ejercicio 1

El hormigón es el material más importante en la ingeniería civil. La resistencia a la compresión del hormigón es una función altamente no lineal de su edad y sus ingredientes.

El fichero `concrete_data.csv` contiene la siguiente información acerca de diferentes muestras de hormigón:

* Contenido de cemento (`Cement`).
* Contenido de escoria de alto horno (`Blast Furnace Slag`).
* Contenido de cenizas volantes (`Fly Ash`).
* Contenido de agua (`Water`).
* Contenido de superplastificantes (`Superplasticizer`).
* Contenido de agregados gruesos (`Coarse Aggregate`).
* Contenido de agregados finos (`Fine Aggregate`).
* Edad del hormigón (`Age`).

El objetivo es predecir la resistencia a la compresión (`Strength`) a partir de esos atributos continuos.

Se pide realizar lo siguiente:

1. Dividir el conjunto de datos en un subconjunto de entrenamiento y un subconjunto de prueba.
2. Abordar la tarea mediante una red neuronal que tenga una única capa oculta con 16 neuronas y función de activación sigmoide.
3. Entrenar la red durante 50 épocas, usando el error cuadrático medio como función de coste a minimizar.
4. Calcular el rendimiento de la red como el error absoluto medio sobre el conjunto de prueba.
5. Experimentar con distintas arquitecturas de la red (cantidad de capas ocultas, cantidad de neuronas en cada capa oculta, función de activación de las capas) e hiperparámetros de entrenamiento (factor de aprendizaje, tamaño de los minilotes, número de épocas), tratando de encontrar una red con un error absoluto medio sobre el conjunto de prueba menor a 0.1.

In [21]:
# 1. Dividir el conjunto de datos en un subconjunto de entrenamiento y un subconjunto de prueba.
import pandas as pd
dataset = pd.read_csv('concrete_data.csv')
dataset.head()

# --- separar atributos de objetivo
X = dataset.loc[:, 'Cement':'Age'] 
y = dataset.loc[:,'Strength']
(X.shape, y.shape)

# --- dividir en entrenamiento y prueba
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

dataset.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

In [33]:
# 2. Abordar la tarea mediante una red neuronal que tenga una única capa oculta con 16 neuronas y función de activación sigmoide.
from keras import Sequential, Input
from keras.layers import Dense, Normalization

normalizador = Normalization()
normalizador.adapt(X_train.to_numpy())

model = Sequential()
model.add(Input(shape=(8,)))
model.add(normalizador)
model.add(Dense(16, activation='sigmoid'))

model.summary()

Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ normalization_1 (Normalization) │ (None, 8)              │            17 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 16)             │           144 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 161 (648.00 B)

 Trainable params: 144 (576.00 B)

 Non-trainable params: 17 (72.00 B)

In [34]:
# 3. Entrenar la red durante 50 épocas, usando el error cuadrático medio como función de coste a minimizar.

model.compile(optimizer="SGD", loss='mean_squared_error', metrics=["mean_absolute_error"])
model.fit(x=X_train, y=y_train, epochs=50 )

Epoch 1/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1513.5508 - mean_absolute_error: 35.1293
Epoch 2/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1509.4027 - mean_absolute_error: 35.0762
Epoch 3/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1505.5533 - mean_absolute_error: 35.0258
Epoch 4/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1502.0977 - mean_absolute_error: 34.9796
Epoch 5/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1499.1031 - mean_absolute_error: 34.9389
Epoch 6/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1496.5662 - mean_absolute_error: 34.9029
Epoch 7/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1494.4451 - mean_absolute_error: 34.8724
Epoch 8/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1492.7030 - mean_absolute_error: 34.8465
Epoch 9/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1491.2814 - mean_absolute_error: 34.8252
Epoch 10/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1490.1188 - mean_absolute_error: 34.8072
Epoch 11/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1489.1646 - mean_absolute_error: 34.7921
Epoch 12/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1488.3717 - mean_absolute_error: 34.7796
Epoch 13/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1487.7046 - mean_absolute_error: 34.7688
Epoch 14/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1487.1370 - mean_absolute_error: 34.7596
Epoch 15/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1486.6506 - mean_absolute_error: 34.7517
Epoch 16/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1486.2296 - mean_absolute_error: 34.7447
Epoch 17/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1485.8630 - mean_absolute_error: 34.7386
Epoch 18/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1485.5396 - mean_absolute_error: 34.7332
Epoch 19/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1485.2533 - mean_absolute_error: 34.7285
Epoch 20/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1484.9989 - mean_absolute_error: 34.7242
Epoch 21/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1484.7708 - mean_absolute_error: 34.7204
Epoch 22/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1484.5660 - mean_absolute_error: 34.7170
Epoch 23/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1484.3806 - mean_absolute_error: 34.7139
Epoch 24/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1484.2123 - mean_absolute_error: 34.7110
Epoch 25/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1484.0586 - mean_absolute_error: 34.7084
Epoch 26/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1483.9181 - mean_absolute_error: 34.7061
Epoch 27/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1483.7892 - mean_absolute_error: 34.7039
Epoch 28/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1483.6704 - mean_absolute_error: 34.7019
Epoch 29/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1483.5605 - mean_absolute_error: 34.7000
Epoch 30/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1483.4590 - mean_absolute_error: 34.6983
Epoch 31/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1483.3645 - mean_absolute_error: 34.6967
Epoch 32/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1483.2767 - mean_absolute_error: 34.6952
Epoch 33/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1483.1948 - mean_absolute_error: 34.6939
Epoch 34/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1483.1182 - mean_absolute_error: 34.6925
Epoch 35/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1483.0463 - mean_absolute_error: 34.6913
Epoch 36/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1482.9788 - mean_absolute_error: 34.6902
Epoch 37/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1482.9152 - mean_absolute_error: 34.6891
Epoch 38/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1482.8555 - mean_absolute_error: 34.6881
Epoch 39/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1482.7988 - mean_absolute_error: 34.6871
Epoch 40/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1482.7456 - mean_absolute_error: 34.6862
Epoch 41/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1482.6951 - mean_absolute_error: 34.6854
Epoch 42/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1482.6471 - mean_absolute_error: 34.6845
Epoch 43/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1482.6017 - mean_absolute_error: 34.6838
Epoch 44/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1482.5586 - mean_absolute_error: 34.6830
Epoch 45/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1482.5175 - mean_absolute_error: 34.6823
Epoch 46/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1482.4783 - mean_absolute_error: 34.6817
Epoch 47/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1482.4410 - mean_absolute_error: 34.6810
Epoch 48/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1482.4055 - mean_absolute_error: 34.6804
Epoch 49/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1482.3713 - mean_absolute_error: 34.6799
Epoch 50/50
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1482.3387 - mean_absolute_error: 34.6793

In [35]:
# 4.  Calcular el rendimiento de la red como el error absoluto medio sobre el conjunto de prueba.
loss, mae = model.evaluate(X_test,y_test)
print(f"Perdida: {loss}, rendimiento: {mae}")

7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1533.2419 - mean_absolute_error: 35.4926
Perdida: 1533.241943359375, rendimiento: 35.49263000488281

### Ejercicio 1 - Punto 5 (sin scikeras)

Se realiza una búsqueda de hiperparámetros sin `scikeras`, usando Keras puro:

- Se prueban arquitecturas (capas, neuronas y activación).
- Se prueban hiperparámetros de entrenamiento (optimizador, learning rate, batch size y épocas).
- Se selecciona la mejor configuración por MAE en validación.
- Finalmente se evalúa el mejor modelo en test.

In [38]:
import itertools
import random
import numpy as np
import tensorflow as tf

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error

from keras import Sequential
from keras.layers import Dense, Input
from keras.optimizers import SGD, Adam
from keras.callbacks import EarlyStopping

# Reproducibilidad
np.random.seed(42)
tf.random.set_seed(42)
random.seed(42)

# Separar validación a partir del train
X_tr, X_val, y_tr, y_val = train_test_split(
    X_train, y_train, test_size=0.2, random_state=42
)

# Escalado (fit solo con train para evitar fuga de información)
scaler = StandardScaler()
X_tr_s = scaler.fit_transform(X_tr)
X_val_s = scaler.transform(X_val)
X_test_s = scaler.transform(X_test)
X_train_s = scaler.transform(X_train)

def build_model(input_dim, hidden_layers=(16,), activation="relu", optimizer_name="adam", learning_rate=1e-3):
    model = Sequential()
    model.add(Input(shape=(input_dim,)))

    for units in hidden_layers:
        model.add(Dense(units, activation=activation))

    model.add(Dense(1, activation="linear"))

    if optimizer_name == "sgd":
        optimizer = SGD(learning_rate=learning_rate)
    else:
        optimizer = Adam(learning_rate=learning_rate)

    model.compile(
        optimizer=optimizer,
        loss="mean_squared_error",
        metrics=["mean_absolute_error"]
    )
    return model

# Espacio de búsqueda
space = {
    "hidden_layers": [(16,), (32,), (64, 32), (128, 64)],
    "activation": ["relu", "tanh", "sigmoid"],
    "optimizer_name": ["adam", "sgd"],
    "learning_rate": [1e-2, 5e-3, 1e-3, 5e-4],
    "batch_size": [16, 32, 64],
    "epochs": [80, 120, 200]
}

# Generar todas las combinaciones y muestrear un subconjunto
all_configs = list(itertools.product(
    space["hidden_layers"],
    space["activation"],
    space["optimizer_name"],
    space["learning_rate"],
    space["batch_size"],
    space["epochs"]
))

n_trials = 5
sampled = random.sample(all_configs, n_trials)

best_cfg = None
best_val_mae = float("inf")
results = []

for i, cfg in enumerate(sampled, start=1):
    hidden_layers, activation, optimizer_name, lr, batch_size, epochs = cfg

    model = build_model(
        input_dim=X_tr_s.shape[1],
        hidden_layers=hidden_layers,
        activation=activation,
        optimizer_name=optimizer_name,
        learning_rate=lr
    )

    early_stop = EarlyStopping(
        monitor="val_mean_absolute_error",
        patience=15,
        restore_best_weights=True
    )

    model.fit(
        X_tr_s, y_tr,
        validation_data=(X_val_s, y_val),
        epochs=epochs,
        batch_size=batch_size,
        verbose=0,
        callbacks=[early_stop]
    )

    _, val_mae = model.evaluate(X_val_s, y_val, verbose=0)

    results.append({
        "hidden_layers": hidden_layers,
        "activation": activation,
        "optimizer": optimizer_name,
        "learning_rate": lr,
        "batch_size": batch_size,
        "epochs": epochs,
        "val_mae": val_mae
    })

    print(f"[{i:02d}/{n_trials}] val_mae={val_mae:.4f} | cfg={results[-1]}")

    if val_mae < best_val_mae:
        best_val_mae = val_mae
        best_cfg = results[-1]

print("\nMejor configuración (validación):")
print(best_cfg)
print(f"Mejor MAE validación: {best_val_mae:.4f}")

# Entrenamiento final con la mejor configuración sobre TODO X_train
final_model = build_model(
    input_dim=X_train_s.shape[1],
    hidden_layers=best_cfg["hidden_layers"],
    activation=best_cfg["activation"],
    optimizer_name=best_cfg["optimizer"],
    learning_rate=best_cfg["learning_rate"]
)

early_stop_final = EarlyStopping(
    monitor="val_mean_absolute_error",
    patience=20,
    restore_best_weights=True
)

final_model.fit(
    X_train_s, y_train,
    validation_split=0.2,
    epochs=best_cfg["epochs"],
    batch_size=best_cfg["batch_size"],
    verbose=0,
    callbacks=[early_stop_final]
    )

y_pred_test = final_model.predict(X_test_s, verbose=0)
mae_test = mean_absolute_error(y_test, y_pred_test)

print(f"\nMAE en test (rendimiento final): {mae_test:.4f}")
if mae_test < 0.1:
    print("Objetivo alcanzado: MAE < 0.1")
else:
    print("Objetivo NO alcanzado: MAE >= 0.1")

[01/5] val_mae=4.0083 | cfg={'hidden_layers': (128, 64), 'activation': 'relu', 'optimizer': 'adam', 'learning_rate': 0.01, 'batch_size': 64, 'epochs': 80, 'val_mae': 4.008341312408447}
[02/5] val_mae=4.5447 | cfg={'hidden_layers': (16,), 'activation': 'tanh', 'optimizer': 'sgd', 'learning_rate': 0.01, 'batch_size': 64, 'epochs': 80, 'val_mae': 4.544663906097412}
[03/5] val_mae=11.4530 | cfg={'hidden_layers': (16,), 'activation': 'relu', 'optimizer': 'adam', 'learning_rate': 0.001, 'batch_size': 64, 'epochs': 120, 'val_mae': 11.453047752380371}
[04/5] val_mae=3.6794 | cfg={'hidden_layers': (128, 64), 'activation': 'tanh', 'optimizer': 'sgd', 'learning_rate': 0.01, 'batch_size': 32, 'epochs': 80, 'val_mae': 3.6793506145477295}
[05/5] val_mae=4.4863 | cfg={'hidden_layers': (32,), 'activation': 'relu', 'optimizer': 'sgd', 'learning_rate': 0.0005, 'batch_size': 16, 'epochs': 200, 'val_mae': 4.486299991607666}

Mejor configuración (validación):
{'hidden_layers': (128, 64), 'activation': 'tanh', 'optimizer': 'sgd', 'learning_rate': 0.01, 'batch_size': 32, 'epochs': 80, 'val_mae': 3.6793506145477295}
Mejor MAE validación: 3.6794

MAE en test (rendimiento final): 4.0624
Objetivo NO alcanzado: MAE >= 0.1

### Ejercicio 2

El fichero `cars.csv` contiene información acerca de la idoneidad de una serie de coches, en función de los siguientes atributos discretos:

* Precio de compra (`buying`): posibles valores `vhigh`, `high`, `med`, `low`.
* Coste de mantenimiento (`maint`): posibles valores `vhigh`, `high`, `med`, `low`.
* Número de puertas (`doors`): posibles valores `2`, `3`, `4`, `5more`.
* Número de asientos (`persons`): posibles valores `2`, `4`, `more`.
* Tamaño del maletero (`lug_boot`): posibles valores `small`, `med`, `big`.
* Nivel de seguridad estimada (`safety`): posibles valores `low`, `med`, `high`.

La idoneidad de cada coche se indica mediante el atributo `acceptability`, que los clasifica como `unacc`, `acc`, `good` o `vgood`.

Se pide realizar lo siguiente:

1. Dividir el conjunto de datos en un subconjunto de entrenamiento y un subconjunto de prueba.
2. Abordar la tarea mediante una red neuronal que tenga una única capa oculta con 16 neuronas y función de activación tangente hiperbólica.
3. Entrenar la red durante 50 épocas, usando la entropía cruzada categórica como función de coste a minimizar.
4. Calcular el rendimiento de la red como la tasa de acierto sobre el conjunto de prueba.
5. Experimentar con distintas arquitecturas de la red (cantidad de capas ocultas, cantidad de neuronas en cada capa oculta, función de activación de las capas) e hiperparámetros de entrenamiento (factor de aprendizaje, tamaño de los minilotes), tratando de encontrar una red que, entrenada únicamente durante 50 épocas, tenga una tasa de acierto sobre el conjunto de prueba superior a 0.9.

In [63]:
# 1. Dividir el conjunto de datos en Subconjunto de entrenamiento y prueba.
## -- Leer fichero
import pandas as pd
dataset = pd.read_csv('cars.csv')
dataset.head()
## -- Separar atributos y objetivo
X = dataset.iloc[:, :-1]
y = dataset['acceptability']
## -- Divididir entrenamiento y prueba
from sklearn.model_selection import train_test_split
X_train, X_test, y_train_raw, y_test_raw = train_test_split(X, y, test_size=0.2, stratify=objetivo)

# Codificar atributos categóricos
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
ct = ColumnTransformer(
    transformers=[
        ("discretize", OneHotEncoder(handle_unknown="ignore"), X.columns)
    ]
)

X_train = ct.fit_transform(X_train)
X_test = ct.transform(X_test)

# Codificar la clase
le = LabelEncoder()
y_train = le.fit_transform(y_train_raw)
y_test = le.transform(y_test_raw)



dataset.head()

  buying  maint doors persons lug_boot safety acceptability
0  vhigh  vhigh     2       2    small    low         unacc
1  vhigh  vhigh     2       2    small    med         unacc
2  vhigh  vhigh     2       2    small   high         unacc
3  vhigh  vhigh     2       2      med    low         unacc
4  vhigh  vhigh     2       2      med    med         unacc

In [64]:
# 2. Red neuronal de una única capa de 16 neuronas y función de activación tangente hiperbólica
from keras import Sequential, Input
from keras.layers import Dense

model = Sequential()
model.add(Input(shape=(X_train.shape[1],)))
model.add(Dense(16, activation='tanh'))
model.add(Dense(4, activation="softmax"))

model.compile(optimizer='SGD',loss='sparse_categorical_crossentropy', metrics=["accuracy"])

In [65]:
# entrenar durante 50 épocas, con función de perdida entropía cruzada categóricaa
model.fit(X_train,y_train,epochs=50)

Epoch 1/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4175 - loss: 1.2729
Epoch 2/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6657 - loss: 0.9301
Epoch 3/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7062 - loss: 0.8255
Epoch 4/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7142 - loss: 0.7715
Epoch 5/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7185 - loss: 0.7326
Epoch 6/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7272 - loss: 0.7007
Epoch 7/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7359 - loss: 0.6730
Epoch 8/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7431 - loss: 0.6484
Epoch 9/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7518 - loss: 0.6260
Epoch 10/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7576 - loss: 0.6055
Epoch 11/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7663 - loss: 0.5865
Epoch 12/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7779 - loss: 0.5688
Epoch 13/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7836 - loss: 0.5524
Epoch 14/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7923 - loss: 0.5371
Epoch 15/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7959 - loss: 0.5229
Epoch 16/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8068 - loss: 0.5096
Epoch 17/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8104 - loss: 0.4972
Epoch 18/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8191 - loss: 0.4856
Epoch 19/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8249 - loss: 0.4748
Epoch 20/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8278 - loss: 0.4647
Epoch 21/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8314 - loss: 0.4552
Epoch 22/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8350 - loss: 0.4464
Epoch 23/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8386 - loss: 0.4381
Epoch 24/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8394 - loss: 0.4303
Epoch 25/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8437 - loss: 0.4229
Epoch 26/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8488 - loss: 0.4160
Epoch 27/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8517 - loss: 0.4094
Epoch 28/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8546 - loss: 0.4032
Epoch 29/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8567 - loss: 0.3973
Epoch 30/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8589 - loss: 0.3917
Epoch 31/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8589 - loss: 0.3864
Epoch 32/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8589 - loss: 0.3814
Epoch 33/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8589 - loss: 0.3765
Epoch 34/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8603 - loss: 0.3719
Epoch 35/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8603 - loss: 0.3674
Epoch 36/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8611 - loss: 0.3632
Epoch 37/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8625 - loss: 0.3591
Epoch 38/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8632 - loss: 0.3551
Epoch 39/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8647 - loss: 0.3513
Epoch 40/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8654 - loss: 0.3477
Epoch 41/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8669 - loss: 0.3441
Epoch 42/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8690 - loss: 0.3407
Epoch 43/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8698 - loss: 0.3374
Epoch 44/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8698 - loss: 0.3341
Epoch 45/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8712 - loss: 0.3310
Epoch 46/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8734 - loss: 0.3280
Epoch 47/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8748 - loss: 0.3250
Epoch 48/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8748 - loss: 0.3222
Epoch 49/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8770 - loss: 0.3194
Epoch 50/50
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8770 - loss: 0.3166

### Ejercicio 3

Los púlsares son un tipo raro de estrella de neutrones que produce emisiones de radio detectables aquí en la Tierra. Son de considerable interés científico como sondas del espacio-tiempo, el medio interestelar y los estados de la materia.

A medida que los púlsares giran, su haz de emisión recorre el cielo y, cuando cruza nuestra línea de visión, produce un patrón detectable de emisión de radio de banda ancha. Como los púlsares giran rápidamente, este patrón se repite periódicamente. Por tanto, la búsqueda de púlsares implica buscar señales de radio periódicas con grandes radiotelescopios.

Cada púlsar produce un patrón de emisión algo diferente, que varía levemente con cada rotación. Por lo tanto, una detección de señal potencial conocida como «candidata» se promedia a lo largo de muchas rotaciones del púlsar, según lo determinado por la duración de una observación. A falta de información adicional, cada candidato podría describir un púlsar real. Sin embargo, en la práctica, casi todas las detecciones son causadas por interferencias de radiofrecuencia (RFI) y ruido, lo que dificulta encontrar señales legítimas.

El fichero `pulsar_stars.csv` contiene datos acerca de una serie de púlsares reales y de ejemplos espurios producidos por RFI y ruido. Cada candidato se describe mediante ocho atributos continuos extraídos de las señales recibidas.

Se pide construir una red neuronal que permita abordar, con el mayor rendimiento posible, la tarea de de determinar si un candidato es o no un púlsar.

### Ejercicio 4

Los [abulones](https://es.wikipedia.org/wiki/Haliotis) son una familia de moluscos gasterópodos. La edad de cada individuo está correlacionada con el número de anillos de su concha y, por tanto, puede determinarse cortando la concha a través del cono, tiñéndola y contando el número de anillos a través de un microscopio. Este procedimiento requiere mucho tiempo y es propenso a errores, por lo que sería preferible poder determinar la edad directamente a partir de medidas físicas más fáciles de obtener.

El fichero `abalone.csv` contiene la siguiente información de distintos individuos de abulones:

* Sexo (`Sex`): atributo discreto con posibles valores `M` (macho), `F` (hembra) e `I` (infante).
* Longitud (`Length`) en milímetros.
* Diámetro (`Diameter`) en milímetros.
* Altura (`Height`) en milímetros.
* Peso total (`Whole_weight`) en gramos.
* Peso sin la concha (`Shucked_weight`) en gramos.
* Peso intestinal (`Viscera_weight`) en gramos.
* Peso de la concha (`Shell_weight`) en gramos.

Se pide construir una red neuronal que permita abordar, con el mayor rendimiento posible, la tarea de predecir el número de anillos (`Rings`) a partir de los atributos anteriores (entonces bastaría sumar 1.5 a ese número de anillos para obtener la edad, en años, del individuo).